# Generated by Django 4.2.9 on 2024-02-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True, verbose_name='uuid')),
                ('productIdFs', models.IntegerField(verbose_name='productIdFs')),
                ('description', models.CharField(max_length=3000, unique=True, verbose_name='description')),
                ('available_time', models.IntegerField(verbose_name='available_time')),
                ('datetime_start', models.DateField()),
                ('datetime_finish', models.DateField()),
                ('uuid_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
