# Generated by Django 4.2.9 on 2024-03-03 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatedScanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True, verbose_name='uuid')),
                ('username', models.CharField(max_length=100)),
                ('uuid_scanner', models.CharField(max_length=100)),
            ],
        ),
    ]
