# Generated by Django 4.2.9 on 2024-01-31 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_slot'),
        ('rent', '0002_alter_rent_datetime_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='uuid_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stations.bike'),
        ),
    ]
