# Generated by Django 3.2.5 on 2024-02-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0003_alter_rent_uuid_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='datetime_finish',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='datetime_start',
            field=models.DateTimeField(),
        ),
    ]
