# Generated by Django 4.2.9 on 2024-01-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(editable=False, max_length=36, unique=True, verbose_name='uuid')),
                ('sname', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('batery', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=20, max_digits=30)),
                ('lng', models.DecimalField(decimal_places=20, max_digits=30)),
            ],
        ),
    ]
